name: Semgrep
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    # random HH:MM to avoid a load spike on GitHub Actions at 00:00
    - cron: '12 6 * * *'
jobs:
  scan:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci

  jsutify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Get PR comments
        id: get_comments
        run: |
          github.actions.comment.list issue_number=${{ github.event.number }} owner=${{ github.repository_owner }} repo=${{ github.repo }} > comments.json

      - name: Check for ignored findings without justification
        run: |
          ignored_findings=$(jq '.comments[] | select(.body | contains("Semgrep")) | select(.body | not contains("fix") | not contains("false positive") | not contains("wontfix"))' comments.json)
          if [[ $ignored_findings != "[]" ]]; then
            echo "Found ignored Semgrep findings without justification:"
            echo "$ignored_findings"
            exit 1  # This will cause the job to fail
          else
            echo "No ignored Semgrep findings found without justification."
          fi

      - name: Notify reviewers (Optional)
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.createComment(context.issue.number, {
              body: "**Attention! There are ignored Semgrep findings in this PR without justification. Please review the comments and address them before merging.**"
            })

      - name: Block merge (Optional)
        if: failure()
        uses: gr2m/fail-workflow@v2
        with:
          message: "Semgrep findings ignored without justification. Please provide a reason."






# name: Semgrep
# on:
#   workflow_dispatch: {}
#   pull_request: {}
#   push:
#     branches:
#       - main
#       - master
#     paths:
#       - .github/workflows/semgrep.yml
#   schedule:
#     # random HH:MM to avoid a load spike on GitHub Actions at 00:00
#     - cron: '12 6 * * *'
# jobs:
#   semgrep:
#     name: semgrep/ci
#     runs-on: ubuntu-20.04
#     env:
#       SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
#     container:
#       image: semgrep/semgrep
#     if: (github.actor != 'dependabot[bot]')
#     steps:
#       - uses: actions/checkout@v3
#       - run: semgrep ci